<a href="https://colab.research.google.com/github/eiyu18/MachineLearning/blob/main/JS05/JS05_Assignment02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/sample_data/spam.csv', encoding='latin-1')
df = df.drop(df.iloc[:, 2:], axis=1)
df.columns = ['Labels', 'SMS']

print(df['Labels'].value_counts())
df.head()

Labels
ham     4825
spam     747
Name: count, dtype: int64

  Labels                                                SMS
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
new_labels = {
    'spam': 1,
    'ham': 0
}

df['Labels'] = df['Labels'].map(new_labels)

X = df['SMS'].to_numpy(dtype=object)
y = df['Labels'].to_numpy()

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

bow = CountVectorizer(stop_words='english')

X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

print(f'Number of features: {len(bow.get_feature_names_out())}')
print(f'Data dimensions: {X_train_bow.shape}')

Number of features: 7466
Data dimensions: (4457, 7466)

In [6]:
mnb_bow = MultinomialNB()
mnb_bow.fit(X_train_bow, y_train)

y_pred_train_bow = mnb_bow.predict(X_train_bow)
y_pred_test_bow = mnb_bow.predict(X_test_bow)

acc_train_bow = accuracy_score(y_train, y_pred_train_bow)
acc_test_bow = accuracy_score(y_test, y_pred_test_bow)

print(f'Training data accuracy: {acc_train_bow}')
print(f'Test data accuracy: {acc_test_bow}')
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred_test_bow))
print('Classification Report:\n', classification_report(y_test, y_pred_test_bow))

Training data accuracy: 0.9946152120260264
Test data accuracy: 0.9829596412556054
Confusion Matrix:
 [[951   3]
 [ 16 145]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       954
           1       0.98      0.90      0.94       161

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print(f'Number of features: {len(tfidf.get_feature_names_out())}')
print(f'Data dimensions: {X_train_tfidf.shape}')

Number of features: 7466
Data dimensions: (4457, 7466)

In [8]:
mnb_tfidf = MultinomialNB()
mnb_tfidf.fit(X_train_tfidf, y_train)

y_pred_train_tfidf = mnb_tfidf.predict(X_train_tfidf)
y_pred_test_tfidf = mnb_tfidf.predict(X_test_tfidf)

acc_train_tfidf = accuracy_score(y_train, y_pred_train_tfidf)
acc_test_tfidf = accuracy_score(y_test, y_pred_test_tfidf)

print(f'Training data accuracy: {acc_train_tfidf}')
print(f'Test data accuracy: {acc_test_tfidf}')
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred_test_tfidf))
print('Classification Report:\n', classification_report(y_test, y_pred_test_tfidf))

Training data accuracy: 0.9842943684092439
Test data accuracy: 0.9605381165919282
Confusion Matrix:
 [[954   0]
 [ 44 117]]
Classification Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98       954
           1       1.00      0.73      0.84       161

    accuracy                           0.96      1115
   macro avg       0.98      0.86      0.91      1115
weighted avg       0.96      0.96      0.96      1115

In [9]:
from sklearn.metrics import precision_score, recall_score, f1_score

results = pd.DataFrame({
    'Feature': ['CountVectorizer (stop words)', 'TF-IDF (stop words)'],
    'Train Accuracy': [acc_train_bow, acc_train_tfidf],
    'Test Accuracy': [acc_test_bow, acc_test_tfidf],
    'Spam Precision': [precision_score(y_test, y_pred_test_bow), precision_score(y_test, y_pred_test_tfidf)],
    'Spam Recall': [recall_score(y_test, y_pred_test_bow), recall_score(y_test, y_pred_test_tfidf)],
    'Spam F1': [f1_score(y_test, y_pred_test_bow), f1_score(y_test, y_pred_test_tfidf)]
})
results

,Feature,Train Accuracy,Test Accuracy,Spam Precision,Spam Recall,Spam F1
0,CountVectorizer (stop words),0.994615,0.982960,0.97973,0.900621,0.938511
1,TF-IDF (stop words),0.984294,0.960538,1.00000,0.726708,0.841727